mode: balance
containers:
  - address: http://localhost:5700
    username: admin
    password: admin
    weigth:
    mode: balance
    limit: 9999
theme: ./theme/kuduan.html
static: ./static
master:
database:
qywx_key:
daily_push:
resident:
user_agent:
telegram_bot_token:
telegram_user_id:
qquid:
qqgid:
qbot_public_mode: true
default_priority: 1
no_ghproxy: true
daily_asset_push_cron: 0 10 * * *
repos:
  - git: https://github.com/shufflewzc/faker2.git